### ISSUE TITLE
Update to actions/core v1.10 to fix potential deprecation warnings

### ISSUE THREAD

**Issue by svenstaro** [peter-evans/rust-wasm-action#43]
According to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/, GitHub released a new version of their actions lib which will internally set its state differently and it's my understanding that if it's not updated, the actions will print warnings during execution.

**Comment by peter-evans** [comment]
Hi @svenstaro 

I've already upgraded to `v1.10` here: https://github.com/peter-evans/rust-wasm-action/commit/0293f1bf73eac1232a43a08414fdf93b2bc65dff

I'm not seeing related warnings in the build after that merge.

**Comment by svenstaro** [comment]
Ah yes, though I was referring to this one right here: https://github.com/peter-evans/rust-wasm-action/blob/827aa4bf24379b96571a3d8660b0a0f00c4f7880/actions-toolkit-bindings/package.json#L3

I reckon those should probably be synced.

**Comment by peter-evans** [comment]
Ah you are right. I forgot about that one. I've bumped it in https://github.com/peter-evans/rust-wasm-action/pull/44

Thank you!
